import { randomUUID } from "node:crypto";

import { hashPassword } from "../lib/password";

// Prints ready-to-paste SQL that bootstraps production: the currencies plus one super_admin.
// For operators who'd rather run SQL in the Neon console than hand a database URL to a script —
// nothing here connects to a database, so the connection string never leaves your machine.
//
// The reason this generator exists at all: passwords are argon2id (@node-rs/argon2, see
// lib/password). Postgres cannot compute that — pgcrypto offers md5/sha/bcrypt, not argon2 — so
// a hand-written INSERT would store a plaintext or wrongly-hashed "password" and Better Auth's
// verify() would reject it forever. The hash is computed HERE, with the app's exact parameters,
// and embedded in the SQL as a literal.
//
// Usage:
//   ADMIN_EMAIL=you@x.com ADMIN_PASSWORD='...' ADMIN_NAME='You' pnpm db:admin-sql > admin.sql
// then paste admin.sql into the Neon SQL Editor. Idempotent: re-running updates the password.

const CURRENCIES = [
  { code: "USD", name: "US Dollar", symbol: "$", type: "fiat", rate: 1, isDefault: true, autoWallet: true },
  { code: "EUR", name: "Euro", symbol: "€", type: "fiat", rate: 0.96, isDefault: false, autoWallet: false },
  { code: "GBP", name: "British Pound", symbol: "£", type: "fiat", rate: 0.79, isDefault: false, autoWallet: false },
  { code: "NGN", name: "Nigerian Naira", symbol: "₦", type: "fiat", rate: 1580, isDefault: false, autoWallet: false },
  { code: "USDT", name: "Tether", symbol: "₮", type: "crypto", rate: 1, isDefault: false, autoWallet: false },
];
const ROLES = ["sender", "voucher", "payment", "withdraw"];

// Single-quote escaping for SQL literals. The argon2 hash contains $ and / but never a quote;
// a password never reaches the SQL at all (only its hash does).
const q = (value: string) => `'${value.replace(/'/g, "''")}'`;

function requireEnv(name: string): string {
  const value = process.env[name]?.trim();
  if (!value) throw new Error(`${name} is required.`);
  return value;
}

async function main() {
  const email = requireEnv("ADMIN_EMAIL").toLowerCase();
  const password = requireEnv("ADMIN_PASSWORD");
  const name = process.env.ADMIN_NAME?.trim() || "Admin";

  if (password.length < 8) throw new Error("ADMIN_PASSWORD must be at least 8 characters.");
  if (["12345678", "ChangeMe123!", "password"].includes(password)) {
    throw new Error("ADMIN_PASSWORD is a known default — choose a real one.");
  }

  const hash = await hashPassword(password);
  const userId = randomUUID();
  const accountId = randomUUID();
  const username = email.split("@")[0].replace(/[^a-z0-9_]/gi, "").toLowerCase();

  const lines: string[] = [];
  lines.push("-- Production bootstrap: currencies + one super_admin.");
  lines.push("-- Generated by scripts/print-admin-sql.ts. The password is already argon2id-hashed");
  lines.push("-- with the app's parameters — this file contains NO plaintext password.");
  lines.push("-- Safe to re-run: every statement is idempotent.");
  lines.push("BEGIN;");
  lines.push("");

  lines.push("-- Currencies. Signup derives every user's primary wallet from the default one,");
  lines.push("-- so at least the USD row must exist before anyone registers.");
  for (const c of CURRENCIES) {
    lines.push(
      `INSERT INTO currencies (id, code, name, symbol, type, rate, auto_wallet, is_default, is_active, created_at, updated_at)\n` +
        `VALUES (gen_random_uuid(), ${q(c.code)}, ${q(c.name)}, ${q(c.symbol)}, ${q(c.type)}, ${c.rate}, ${c.autoWallet}, ${c.isDefault}, true, now(), now())\n` +
        `ON CONFLICT (code) DO NOTHING;`,
    );
  }
  lines.push("");
  lines.push("-- Per-role fee/limit config for each currency.");
  lines.push(
    `INSERT INTO currency_roles (id, currency_id, role, fee_type, fee_value, min_amount, max_amount, enabled)\n` +
      `SELECT gen_random_uuid(), c.id, r.role, 'percent', 1.5, 1, 10000, true\n` +
      `FROM currencies c CROSS JOIN (VALUES ${ROLES.map((r) => `(${q(r)})`).join(", ")}) AS r(role)\n` +
      `ON CONFLICT (currency_id, role) DO NOTHING;`,
  );
  lines.push("");

  lines.push("-- The admin. emailVerified + status active are what the login gate checks.");
  lines.push(
    `INSERT INTO "user" (id, name, email, "emailVerified", role, status, username, currency, "kycStatus", "createdAt", "updatedAt")\n` +
      `VALUES (${q(userId)}, ${q(name)}, ${q(email)}, true, 'super_admin', 'active', ${q(username)}, 'USD', 'approved', now(), now())\n` +
      `ON CONFLICT (email) DO UPDATE SET role = 'super_admin', status = 'active', "emailVerified" = true;`,
  );
  lines.push("");

  lines.push("-- Better Auth keeps the password on the credential ACCOUNT row, not on the user.");
  lines.push("-- Without this the admin exists but cannot sign in.");
  lines.push("--");
  lines.push("-- Guarded with NOT EXISTS rather than ON CONFLICT: account's only unique index is");
  lines.push("-- (id), and a re-generated script carries a fresh uuid, so ON CONFLICT (id) would");
  lines.push("-- never fire and would insert a SECOND credential row. Better Auth resolves the");
  lines.push("-- credential account with a findFirst, so duplicates make which password works");
  lines.push("-- arbitrary. One row per (userId, 'credential') is the real invariant.");
  lines.push(
    `INSERT INTO account (id, "accountId", "providerId", "userId", password, "createdAt", "updatedAt")\n` +
      `SELECT ${q(accountId)}, u.id, 'credential', u.id, ${q(hash)}, now(), now()\n` +
      `FROM "user" u WHERE u.email = ${q(email)}\n` +
      `  AND NOT EXISTS (\n` +
      `    SELECT 1 FROM account a WHERE a."userId" = u.id AND a."providerId" = 'credential'\n` +
      `  );`,
  );
  lines.push("");
  lines.push("-- Re-run safety: if the account already existed, reset its password to this hash.");
  lines.push("-- Re-running this script is therefore also how you rotate the admin password.");
  lines.push(
    `UPDATE account SET password = ${q(hash)}, "updatedAt" = now()\n` +
      `WHERE "providerId" = 'credential' AND "userId" = (SELECT id FROM "user" WHERE email = ${q(email)});`,
  );
  lines.push("");

  lines.push("-- The admin's own wallet (the signup hook doesn't run for a row inserted here).");
  lines.push(
    `INSERT INTO wallets (id, user_id, currency, balance_minor, is_default, created_at, updated_at)\n` +
      `SELECT gen_random_uuid(), u.id, 'USD', 0, true, now(), now()\n` +
      `FROM "user" u WHERE u.email = ${q(email)}\n` +
      `ON CONFLICT (user_id, currency) DO NOTHING;`,
  );
  lines.push("");
  lines.push("COMMIT;");
  lines.push("");
  lines.push("-- Verify:");
  lines.push(`--   SELECT email, role, status FROM "user" WHERE email = ${q(email)};`);
  lines.push(`--   SELECT count(*) FROM account WHERE "providerId" = 'credential';`);

  console.log(lines.join("\n"));
}

main().catch((error) => {
  console.error("✗", error instanceof Error ? error.message : error);
  process.exit(1);
});
